name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Generate documentation
        run: npm run docs:generate
      - name: Publish to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1
        with:
          dir: docs
          branch: gh-pages
          token: ${{ secrets.GH_PAT }}
